# Generated by Django 3.2.3 on 2021-06-17 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amazon',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50,serialize=False)),
                ('url', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
