# Generated by Django 3.2.3 on 2021-06-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amazon',
            name='category',
        ),
        migrations.AddField(
            model_name='amazon',
            name='id',
            field=models.BigAutoField(auto_created=True, default=-1.0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='amazon',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
