# Generated by Django 3.2.3 on 2021-06-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0002_auto_20210617_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flipkart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=500)),
                ('price', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
