# Generated by Django 3.2.3 on 2021-06-17 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0003_flipkart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flipkart',
            old_name='email',
            new_name='femail',
        ),
        migrations.RenameField(
            model_name='flipkart',
            old_name='message',
            new_name='fmessage',
        ),
        migrations.RenameField(
            model_name='flipkart',
            old_name='name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='flipkart',
            old_name='price',
            new_name='fprice',
        ),
        migrations.RenameField(
            model_name='flipkart',
            old_name='url',
            new_name='furl',
        ),
    ]
