# Generated by Django 3.2.3 on 2021-06-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0004_auto_20210617_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cowin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50)),
                ('cemail', models.CharField(max_length=50)),
                ('cage', models.CharField(max_length=3)),
                ('cpincode', models.CharField(max_length=7)),
                ('cmessage', models.CharField(max_length=500)),
            ],
        ),
    ]
