# Generated by Django 3.2.3 on 2021-06-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0005_cowin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.CharField(max_length=50)),
                ('hemail', models.CharField(max_length=50)),
                ('hsubject', models.CharField(max_length=100)),
                ('hmessage', models.CharField(max_length=500)),
            ],
        ),
    ]
