# Generated by Django 3.2.3 on 2021-06-18 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0006_help'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amazon',
            old_name='price',
            new_name='arate',
        ),
        migrations.RenameField(
            model_name='amazon',
            old_name='email',
            new_name='sender',
        ),
    ]
