# Generated by Django 3.2.3 on 2021-06-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0007_auto_20210618_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=50)),
                ('rage', models.CharField(max_length=3)),
                ('remail', models.CharField(max_length=50)),
                ('rcontact', models.CharField(max_length=12)),
                ('raddress', models.CharField(max_length=200)),
            ],
        ),
    ]
